### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by ldwstyle** [amibug/hoc-auth#1]
npm install 之后，npm run  precommit，然后报错，错误信息如下：

npm ERR! missing script: lint

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lvdongwei\AppData\Roaming\npm-cache\_logs\2018-08-03T08_54_21_109Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoc-auth@1.0.0 precommit: `npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hoc-auth@1.0.0 precommit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lvdongwei\AppData\Roaming\npm-cache\_logs\2018-08-03T08_54_21_380Z-debug.log

请问还需要安装其他的依赖吗？

**Comment by amibug** [comment]
package.json中没有写lint命令导致， fixed

**Comment by ldwstyle** [comment]
那请问如何启动项目呢？
